### ISSUE TITLE
Add documentation in case build fails from nvim

### ISSUE THREAD

**Issue by mokanfar** [pbogut/magento2-ls#14]
Thanks for your consideration and efforts on this project. Works great. 

While following your documentation to install this on `nvim`, I ran into build errors, so I had to manually get my binary version from [releases](https://github.com/pbogut/magento2-ls/releases/), put it in the directory your plugin is trying to load it from, And finally rename this binary to `magento-ls`.  Can we add that in the documentation / README of your project? Let me know if you want me to do a pull request for this. Thanks again!

**Comment by pbogut** [comment]
Did you try `require('magento2_ls').get_server()` ? Did it fail as well?
This is in documentation and it should do what you did manually. It should download binnary from releases github page and put it in right place.

Ideally I would add this to Mason and lsp-config, but didn't get around to doing that yet.

**Comment by mokanfar** [comment]
@pbogut yes get_server() failed as well

```
E5108: Error executing lua ...n/.local/share/nvim/lazy/magento2-ls/lua/magento2_ls.lua:43: attempt to concatenate a nil value
stack traceback:
	...n/.local/share/nvim/lazy/magento2-ls/lua/magento2_ls.lua:43: in function 'get_package'
	...n/.local/share/nvim/lazy/magento2-ls/lua/magento2_ls.lua:64: in function 'get_bin_name'
	...n/.local/share/nvim/lazy/magento2-ls/lua/magento2_ls.lua:73: in function 'get_bin_url'
	...n/.local/share/nvim/lazy/magento2-ls/lua/magento2_ls.lua:111: in function 'get_server'
	[string ":lua"]:1: in main chunk
```

**Comment by pbogut** [comment]
Fair enogh.

Could you please send me output of:
```
lua vim.print(vim.loop.os_uname())
```
I could then fix `get_server()` function.

As for README update, if you fancy you can add something like "Troubleshooting" or "Known issues" section between "Requirements" and "Contributing" and put some info how to make it work when you cant compile / download server via plugin.

Still, I would really appreciate output of `os_uname()` function so I can fix it for people with similar systems as yours.

**Comment by mokanfar** [comment]
@pbogut your wish is my command: 
```javascript
{
  machine = "arm64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000"
}
```

**Comment by pbogut** [comment]
@mokanfar Thank you Sir.
