### ISSUE TITLE
LSP - rust error

### ISSUE THREAD

**Issue by jesskuz** [pbogut/magento2-ls#15]
Thanks very much for your work on this project - Very excited to get it working for some Magento work, but seeing an issue on which I'm hoping you could advise.

I've tried running `require('magento2-ls').setup()` in my LSP config with Intelephense both running and not running and am seeing the following error:

```
Starting magento2-ls LSP server
Error: Deserializing initialize params Caused by: invalid type: sequence, expected i32
```

Any ideas on what I might try?

**Comment by pbogut** [comment]
The error seams to be happening because there is something wrong with starting parameters sent to LSP server.
Do you pass anything to `setup()` function? Or do you do something with server capabilities?

Ideally I would like some more context how you initialise the plugin.

**Comment by jesskuz** [comment]
Certainly - I'm using Packer for the initial install.  I `source` the Packer config only before when running `PackerSync`, but not on every startup of Vim.

Using Nvim 0.10.0-dev.

```
use({ 'pbogut/magento2-ls', 
  run = "require'magento2_ls'.build()" ,
  config = "require'magento2_ls'.setup()" 
})
```

I have also tried installing with `require'magento2_ls'.get_server()`.

This line is in my `~/.config/nvim/after/plugin/lsp.lua` file.  I haven't added an specific parameters there.

```
require("magento2_ls").setup()
```

After opening any `xml` config file, I get the following errors:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:486: RPC[Error]
code_name = ParseError, 
message = "Message could not be parsed." 
data = {
message = "java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.capabilities.textDocument.completion.completionItemKind.valueSet[0]"
}
stack traceback:
[C]: in function 'assert'
/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:486: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
...
Press ENTER or type command to continue
Client magento2-ls quit with exit code 1 and signal 0. Check log for errors: ~/.local/state/nvim/lsp.log                                                                                                                                                                                                        Press ENTER or type command to continue
```

From LspLog:
```
.../vim/lsp/rpc.lua:794    "rpc"   "~/.local/share/nvim/site/pack/packer/start/magento2-ls/lua/../target/release/magento2-ls"   "stderr"    "Starting magento2-ls LSP server\n"

.../vim/lsp/rpc.lua:794    "rpc"   "~/.local/share/nvim/site/pack/packer/start/magento2-ls/lua/../target/release/magento2-ls"   "stderr"    "Error: Deserializing initialize params\n\nCaused by:\n"
                                                                                              
 .../vim/lsp/rpc.lua:794    "rpc"   "~/.local/share/nvim/site/pack/packer/start/magento2-ls/lua/../target/release/magento2-ls"   "stderr"    "    invalid type: sequence, expected i32\n"
```
 
I also confirmed that the above `magento2-ls` binary exists in the `target/release` directory.

Checking the working directory using `:lua print(vim.fn.getcwd())`, I see that it's set to the root of my Magento 2 project.  Would it help to add a `root_dir` setup parameter to the LSP config? 

Intelephense does work as expected, but the last thing I tried was commenting out all other LSP setups, leaving only this module, to see if anything else was interfering.

Thank you.

**Comment by pbogut** [comment]
Looks like it's something with your config, maybe something with completion settings judging by this error:

```
java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.capabilities.textDocument.completion.completionItemKind.valueSet[0]"
```

It's from some LSP written in Java. It says it gets array instead of string. Error from rust (Magento LSP) says it gets array instead of integer. My guess is that you have misconfigured LSP in nvim and it affects multiple language servers. 

Either try comenting LSP related settings plugins and then go back from there, or check on clean config.

**Comment by jesskuz** [comment]
I've deleted my nvim config, removed all other LSPs and plugins, reinstalled `magento2_ls` using `packer.lua` and built with `cargo build --release`.  Here is the error I'm getting when opening an XML file:

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:477: Error executing lua: vim/keymap.lua:0: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        vim/keymap.lua: in function 'del'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:480: in function </usr/local/share/nvim/runtime/lua/vim/lsp.lua:477>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:477: in function 'reset_defaults'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:523: in function </usr/local/share/nvim/runtime/lua/vim/lsp.lua:509>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:477: in function 'reset_defaults'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:523: in function </usr/local/share/nvim/runtime/lua/vim/lsp.lua:509>
Press ENTER or type command to continue
Client magento2-ls quit with exit code 1 and signal 0. Check log for errors: ~/.local/state/nvim/lsp.log
Press ENTER or type command to continue
```

I also tried reverting to Nvim v0.6.1, which yielded the following error:

```
Error in packer_compiled: ...m/site/pack/packer/start/magento2-ls/lua/magento2_ls.lua:93: attempt to call field 'nvim_create_augroup' (a nil value)
Please check your config for correctness
Error detected while processing ~/.config/nvim/after/plugin/lsp.lua:
E5113: Error while calling lua chunk: ...m/site/pack/packer/start/magento2-ls/lua/magento2_ls.lua:93: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/magento2-ls/lua/magento2_ls.lua:93: in function 'setup'
        ~/.config/nvim/after/plugin/lsp.lua:1: in main chunk
```

Same error is registered in `lsp.log`.  Any further thoughts?

Wondering if I'm missing something.  Do I need null-ls installed perhaps?

**Comment by pbogut** [comment]
Nvim v0.6.1 is just too old for the plugin as its using `nvim_create_augroup` which was introduce later. You an still use lsp, but you would have configure lsp manually.
As for first error, I'm not sure what version of neovim it was, but it looks like you have problem with configuration.

Issues reported here have nothing to do with the plugin itself (or lsp server), your configuration is over all not quite right and you are getting errors. If your neovim configuration is not too crazy and you can share it then I can have a look, maybe I will spot where is the problem.

I can recommend https://github.com/nvim-lua/kickstart.nvim for neovim configuration, either if you want to start over or just have a point of reference to how things are configured.

Also, if you want to confirm that LSP server works correctly you can try it in VS Code (can be installed from VSCode extention tab, or whatever its called there), if it works there then you can be sure that server is working all right and the problem is somewhere in Neovim configuration.

**Comment by jesskuz** [comment]
Indeed, something was probably interfering in my config.  I've tried a completely new config using kickstart with no custom additions except for adding the installation in the lazyvim config:
```
  {
    'pbogut/magento2-ls',
    -- Build using cargo build --release
    run = "require'magento2_ls'.build()",
    -- Alternatively, you can download the compiled binary from the GitHub release.
    -- run = "require'magento2_ls'.get_server()" ,
    config = "require'magento2_ls'.setup()",
  },
```

No more LspLog errors :-)  So I will review my previous config.

Only other question I have is whether the plugin uses the built-in LSP jump-to definition/declaration/implementations functions to link the XML definitions.  I've enabled the mouse to test and seeing the following:

```
E433: No tags file                     
E426: Tag not found: Configuration     
Press ENTER or type command to continue
```

Should I try generating a tags file with ctags?  Or might this work with the indexing provided by an LSP, like Intelephense or phpactor?

Thanks very much again.

**Comment by jesskuz** [comment]
I got it working with `kickstart`.  I still built manually using `cargo build --release`.
Both the XML and JS module jumps are working!  Excellent.

This config worked in the lazy.vim config section -

```
{                                          
  'pbogut/magento2-ls',                    
  run = function()                         
    require('magento2_ls').build()         
  end,
  config = function()                      
    require('magento2_ls').setup()         
  end,                                     
},                                         
```

Something in my previous configuration must have been interfering.
Thanks again.
